version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-ecr: circleci/aws-ecr@8.2.1
  docker: circleci/docker@1.4.0

jobs:
  setup-project:
    docker:
      - image: node
        auth: 
          username: m4theusp
          password: dckr_pat_7wtc-LJeZ4wu9fpPY4rRohgojG0
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "install depenpendencies"
          command: yarn install
      - run:
          name: "generate schemas"
          command: npx prisma generate
      - run:
          name: "build project"
          command: yarn build
      - run:
          name: "running tests"
          command: yarn test
         
workflows:
  say-hello-workflow:
    jobs:
      - setup-project


    